version: '3.7'

services:
  matomo:
    image: matomo:4
    container_name: matomo
    restart: unless-stopped
    env_file: ./secrets/MATOMO_SECRET_ENV
    depends_on:
      # - mysql
      - proxy
    environment:
      - MATOMO_DATABASE_HOST=analytics-1.cryruszpxgql.us-east-2.rds.amazonaws.com
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=matomo
      - TZ=America/Indiana/Indianapolis
    networks:
      - analytics
    # Expose via the reverse proxy
    # ports:
    #   - 8080:80/tcp
    volumes:
      - matomo:/var/www/html

  proxy:
    image: trace/haproxy
    build:
      context: ./haproxy
    container_name: proxy
    restart: unless-stopped
    environment:
      - TZ=America/Indiana/Indianapolis
    networks:
      - public
      - analytics
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./haproxy/certs:/certs:ro

  # mysql:
  #   image: trace/mysql
  #   build:
  #     context: mysql
  #   container_name: mysql
  #   restart: unless-stopped
  #   environment:
  #     - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
  #     - TZ=America/Indiana/Indianapolis
  #   secrets:
  #     - MYSQL_ROOT_PASSWORD
  #     - MATOMO_SECRET_ENV
  #   networks:
  #     - analytics
  #   # Accessed via the docker network
  #   # Doesn't need to be exposed on the host
  #   # ports:
  #   #   - 3306:3306/tcp
  #   volumes:
  #     - mysql:/var/lib/mysql

secrets:
  MATOMO_SECRET_ENV:
    file: ./secrets/MATOMO_SECRET_ENV
  # MYSQL_ROOT_PASSWORD:
  #   file: ./secrets/MYSQL_ROOT_PASSWORD

networks:
  public:
    driver: bridge
  analytics:
    driver: bridge

volumes:
  matomo:
  mysql:
  certs:
